#include "cpmdc_features.h"
#include <string.h>

#define CPMDC_PARAM_FEATURE(id) {id, CPMDC_FEATURE_PARAMS, 1, 1}

static const CPMDCFeatureEntry g_features[] = {
    {"section.generic", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.atom", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.system", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.cpmd", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.dft", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.atoms", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.basis", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.clas", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.eam", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.exte", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.hardness", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.info", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.linres", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.molstates", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.mts", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.nlcc", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.path", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.pimd", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.potential", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.prop", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.ptddft", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.resp", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.tddft", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.vdw", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.vectors", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.wavefunction", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.set", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.raw", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.ATOM", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.ATOMS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.BASIS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.CLAS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.CPMD", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.DFT", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.EAM", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.EXTE", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.HARDNESS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.INFO", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.LINRES", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.MOLSTATES", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.MTS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.NLCC", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.PATH", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.PIMD", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.POTENTIAL", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.PROP", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.PTDDFT", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.RESP", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.SYSTEM", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.TDDFT", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.VDW", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.VECTORS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.WAVEFUNCTION", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.cpmd.OPTIMIZE_WAVEFUNCTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.OPTIMIZE_GEOMETRY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_CP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_BO", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_EH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_PT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_CLASSICAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_FILE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.EMASS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TIMESTEP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MAXSTEP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MAXITER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_ORBITALS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_GEOMETRY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_ELECTRONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BERENDSEN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LANGEVIN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ANNEALING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.QUENCH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RATTLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SHAKE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONSTRAINT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TROTTER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RESTART", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RESTART_WAVEFUNCTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRAJECTORY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRINT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STORE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CENTER_MOLECULE_OFF", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CENTER_MOLECULE_ON", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIIS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ODIIS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PCG", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIAGONALIZATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FREE_ENERGY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.INTERFACE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.QMMM", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BICANONICAL_ENSEMBLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CDFT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PROPERTIES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VDW_CORRECTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VDW_WANNIER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DCACP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ISOLATED_MOLECULE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_LDA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_BONLY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_BP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_BP86", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_BLYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_GGA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PW91", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PBE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_REVPBE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_HCTH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_OPTX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_OLYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_XLYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_B3LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_B1LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PBE0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_REVPBE0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PBES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PBE1W", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_TPSS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_HARTREE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_HARTREE_FOCK", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_HSE06", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_ACM0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_ACM1", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_ACM3", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.LSD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.GC_CUTOFF", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.OLDCODE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.NEWCODE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.XC_DRIVER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.LIBXC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.LR_KERNEL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.REFUNCT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.MTS_HIGH_FUNC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.MTS_LOW_FUNC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HFX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HFX_SCREENING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HUBBARD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.CORRELATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.EXCHANGE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.BECKE88", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.ALPHA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.BETA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"params.functional", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.cutOffRy", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.charge", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.multiplicity", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.task", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.title", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.memoryMb", CPMDC_FEATURE_PARAMS, 1, 0},
    {"params.scratchDir", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.permanentDir", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.cpmdRoot", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.enginePath", CPMDC_FEATURE_PARAMS, 1, 0},
    {"params.inputBlocks", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.inputSections", CPMDC_FEATURE_PARAMS, 1, 1},
    CPMDC_PARAM_FEATURE("params.inputSections.generic.name"),
    CPMDC_PARAM_FEATURE("params.inputSections.generic.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.atom.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.atom.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.symmetry"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.angstrom"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.referenceCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.classicalCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.isotropicCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.zFlexibleCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.checkSymmetryPrecision"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.checkSymmetryOff"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cutOffRy"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cutoffShape"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.hfxCutoff"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.scale"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.scaleCartesian"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.charge"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.multiplicity"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.nSup"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.states"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.occupation"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.occupationFixed"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.externalField"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.wCut"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.wGauss"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.pointGroup"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.pointGroupMolecule"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.pointGroupDelta"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.lowSpinExcitation"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.lowSpinExcitationLsets"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.lseParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.modifiedGoedecker"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.modifiedGoedeckerParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.energyProfile"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.densityCutOffRy"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.densityCutoffNumber"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.dual"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.constantCutoff"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.boxWalls"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.poissonSolver"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.poissonParameter"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.mesh"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.doubleGrid"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.symmetrizeCoordinates"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.tesr"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.surface"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.polymer"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cluster"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.pressure"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.stressTensor"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.shockVelocity"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.basis.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.basis.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.optimizeWavefunction"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamics"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceOrbitals"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.maxStep"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.timestep"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.restartWavefunction"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trajectory"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.optimizeGeometry"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.maxIter"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceGeometry"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.electronMass"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsCp"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsBo"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsEh"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsPt"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.molecularDynamicsClassical"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsFile"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nose"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseIons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseElectrons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.berendsen"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.langevin"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.annealing"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.quench"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rattle"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.shake"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.constraint"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trotter"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.restart"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.printOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.storeOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.centerMoleculeOff"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.centerMoleculeOn"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.diis"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.odiis"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.pcg"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.diagonalization"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.freeEnergy"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.interface"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.qmmm"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.bicanonicalEnsemble"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cdft"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.properties"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vdwCorrection"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vdwWannier"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.dcacp"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.isolatedMolecule"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.functional"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.lsd"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.gcCutoff"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.xcDriver"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.libxc"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.lrKernel"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.refunct"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.mtsHighFunc"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.mtsLowFunc"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.hfx"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.hfxScreening"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.hubbard"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.alpha"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.beta"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.oldCode"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.newCode"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.correlation"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.exchange"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.becke88"),
    CPMDC_PARAM_FEATURE("params.inputSections.clas.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.clas.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.eam.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.eam.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.exte.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.exte.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.hardness.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.hardness.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.info.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.info.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.linres.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.linres.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.molstates.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.molstates.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.mts.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.mts.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.nlcc.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.nlcc.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.path.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.path.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.pimd.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.pimd.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.potential.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.potential.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.prop.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.prop.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.ptddft.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.ptddft.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.resp.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.resp.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.tddft.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.tddft.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.vdw.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.vdw.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.vectors.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.vectors.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.wavefunction.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.wavefunction.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.atoms.pseudopotentials"),
    CPMDC_PARAM_FEATURE("params.inputSections.atoms.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.set.key"),
    CPMDC_PARAM_FEATURE("params.inputSections.set.value"),
    CPMDC_PARAM_FEATURE("params.inputSections.raw"),
    {"abi.cpmdc_set_params", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_energy_gradient", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_energy", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_energy_forces", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_create", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_set_params", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_destroy", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_energy_gradient", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_energy", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_energy_forces", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_calculate_forces", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_calculate_result", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_calculate_result", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_potential_result_size_for_force_input", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_version", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_available", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_finalize", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_feature_count", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_feature_table", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_feature_find", CPMDC_FEATURE_ABI, 1, 1},
};

#undef CPMDC_PARAM_FEATURE

size_t cpmdc_feature_count(void) {
  return sizeof(g_features) / sizeof(g_features[0]);
}

const CPMDCFeatureEntry *cpmdc_feature_table(void) { return g_features; }

const CPMDCFeatureEntry *cpmdc_feature_find(const char *feature_id) {
  if (!feature_id) return NULL;
  size_t n = cpmdc_feature_count();
  for (size_t i = 0; i < n; ++i) {
    if (strcmp(g_features[i].feature_id, feature_id) == 0)
      return &g_features[i];
  }
  return NULL;
}
