#include "cpmdc_features.h"
#include <string.h>

#define CPMDC_PARAM_FEATURE(id) {id, CPMDC_FEATURE_PARAMS, 1, 1}

static const CPMDCFeatureEntry g_features[] = {
    {"section.generic", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.atom", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.system", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.cpmd", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.dft", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.atoms", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.basis", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.clas", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.eam", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.exte", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.hardness", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.info", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.linres", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.molstates", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.mts", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.nlcc", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.path", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.pimd", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.potential", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.prop", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.ptddft", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.resp", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.tddft", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.vdw", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.vectors", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.wavefunction", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.set", CPMDC_FEATURE_SECTION, 1, 1},
    {"section.raw", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.ATOM", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.ATOMS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.BASIS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.CLAS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.CPMD", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.DFT", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.EAM", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.EXTE", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.HARDNESS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.INFO", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.LINRES", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.MOLSTATES", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.MTS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.NLCC", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.PATH", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.PIMD", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.POTENTIAL", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.PROP", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.PTDDFT", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.RESP", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.SYSTEM", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.TDDFT", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.VDW", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.VECTORS", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.section.WAVEFUNCTION", CPMDC_FEATURE_SECTION, 1, 1},
    {"catalog.cpmd.OPTIMIZE_WAVEFUNCTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.OPTIMIZE_GEOMETRY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.OPTIMIZE_GEOMETRY_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.OPTIMIZE_GEOMETRY_SAMPLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.OPTIMIZE_COMBINED", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.OPTIMIZE_COMBINED_SAMPLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_CP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_BO", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_EH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_PT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_CLASSICAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_FILE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_FILE_OPTIONS",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOLECULAR_DYNAMICS_BD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PARRINELLO_RAHMAN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CHEBY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CAYLEY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RUNGE_KUTTA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FORCEMATCH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.EMASS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TIMESTEP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MAXSTEP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MAXITER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_ORBITALS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_GEOMETRY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_ELECTRONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BERENDSEN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LANGEVIN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ANNEALING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DAMPING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.QUENCH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RATTLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SHAKE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONSTRAINT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TROTTER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RESTART", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RESTART_WAVEFUNCTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRAJECTORY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRINT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STRUCTURE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STRUCTURE_SELECTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STORE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_PARAMETER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_OPTIMIZATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_NPROC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_RELOCALIZE_IN_SCF",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_RECOMPUTE_DIPOLE_MATRICES_EVERY",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_RELOCALIZE_EVERY",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_TYPE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_REFERENCE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_SERIAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_DOS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_MOLECULAR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_WFNOUT_OPTIONS",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WANNIER_WFNOUT_PAYLOAD",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PARA_USE_MPI_IN_PLACE",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PARA_BUFF_SIZE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PARA_STACK_BUFF_SIZE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CP_GROUPS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FILE_FUSION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FILE_MERGE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FILE_SEPARATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NO_RESET", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GLOCALIZATION_PARAMETERS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GLOCALIZATION_OPTIMIZATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GFUNCTIONAL_TYPE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SPREAD_RSPACE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.G_UNITARITY_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STEP_TUNING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.G_ANTISYM", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.G_ANTISYM_PENALTY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.G_KICK", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.G_COMPLEX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.G_REAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.READ_MATRIX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.G_STEP_TUNE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GLOC_WFNOUT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NO_GEO_CHECK", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BROKEN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DISTRIBUTED_LINALG", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LINALG_NEWORTHO", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DISORTHO_BSIZE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BLOCKSIZE_STATES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ALLTOALL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GSHELL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LOCAL_POTENTIAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CENTER_MOLECULE_OFF", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CENTER_MOLECULE_ON", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CENTER_MOLECULE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIIS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ODIIS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PCG", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIAGONALIZATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FREE_ENERGY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FREE_ENERGY_FUNCTIONAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.INTERFACE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.QMMM", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BICANONICAL_ENSEMBLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CDFT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CDFT_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CDFT_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CDFT_HDA_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VGFACTOR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VMIRROR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.COMBINE_SYSTEMS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.COMBINE_SYSTEMS_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.COMBINE_SYSTEMS_SAB_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.KSHAM", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.KSHAM_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CZONES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WOUT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.WOUT_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.XFMQC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DEBUG", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DEBUG_CODE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DEBUG_MEMORY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DEBUG_FILEOPEN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DEBUG_FORCES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DEBUG_NOACC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.KOHN_SHAM_ENERGIES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.KOHN_SHAM_ENERGIES_COUNT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SURFACE_HOPPING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ROKS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ROKS_EXPERT_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PATH_SAMPLING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FIXRHO_UPWFN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FIXRHO_VECT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FIXRHO_LOOP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FIXRHO_WFTOL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BOGOLIUBOV_CORRECTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VIBRATIONAL_ANALYSIS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VIBRATIONAL_ANALYSIS_SAMPLE",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VIBRATIONAL_ANALYSIS_MODE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ELECTRONIC_SPECTRA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SPIN_ORBIT_COUPLING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SOC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PROPAGATION_SPECTRA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PROPAGATION_DISTRUB", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GAUGEPULSE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GAUGEFIELD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NACV", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ORBITAL_HARDNESS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PATH_INTEGRAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PATH_MINIMIZATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LANGEVIN_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LANGEVIN_PARAMETER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.QMMMEASY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.INTERFACE_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TROTTER_FACTOR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TROTTER_FACTOR_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TROTTER_FACTORIZATION_OFF",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LINEAR_RESPONSE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.HARMONIC_REFERENCE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.HARMONIC_REFERENCE_SYSTEM",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SCALED_MASSES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TDDFT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SSIC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NONORTHOGONAL_ORBITALS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NONORTHOGONAL_ORBITALS_LIMIT",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LANCZOS_DIAGONALIZATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LANCZOS_PARAMETERS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LANCZOS_PARAMETER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LANCZOS_PARAMETERS_PAYLOAD",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DAVIDSON_DIAGONALIZATION",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DAVIDSON_PARAMETERS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DAVIDSON_PARAMETER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ALEXANDER_MIXING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ANDERSON_MIXING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ANDERSON_MIXING_PAYLOAD",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BROYDEN_MIXING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BROYDEN_MIXING_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIIS_MIXING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIIS_MIXING_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOVERHO", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.EXTRAPOLATE_WFN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.EXTRAPOLATE_WFN_ORDER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.EXTRAPOLATE_CONSTRAINT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TSDE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TSDP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TCGP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TSDC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STEEPEST_DESCENT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONJUGATE_GRADIENT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONJUGATE_GRADIENTS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ODIIS_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ODIIS_VECTORS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.HAMILTONIAN_CUTOFF", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GDIIS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LBFGS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LBFGS_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LBFGS_NTRUST", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LBFGS_NRESTT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LBFGS_NTRSTR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LBFGS_TRUSTR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_MODE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_MDLOCK", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_TOLENV", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_TRUSTP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_OMIN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_NSVIB", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_CORE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_NSMAXP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_PRJHES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_DISPL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRFO_HESSTYPE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.HESSCORE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BFGS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RFO", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RFO_ORDER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.INR_PARAMETERS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.INR_PARAMETERS_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.IMPLICIT_NEWTON", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.IMPLICIT_NEWTON_MAXITER",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MIXSD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MIXDIIS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RESTART_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.INTFILE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.INTFILE_NAME", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.INITIALIZE_WAVEFUNCTION",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RATTLE_PARAMETERS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ORTHOGONALIZATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.QUENCH_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RANDOMIZE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RANDOMIZE_AMPLITUDE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.USE_MTS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NABDY_ZMAX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NABDY_SOFT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NABDY_REDISTR_AMPLI", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NABDY_SCALEP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NABDY_THERMO", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.USE_IN_STREAM", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.USE_OUT_STREAM", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.USE_CUBLAS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.USE_CUFFT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BLAS_N_STREAMS_PER_DEVICE",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BLAS_N_DEVICES_PER_TASK",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FFT_N_STREAMS_PER_DEVICE",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FFT_N_DEVICES_PER_TASK",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.USE_MPI_IO", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRACE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRACE_PROCEDURE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRACE_MAX_DEPTH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRACE_MAX_CALLS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PROPERTIES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VDW_CORRECTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.VDW_WANNIER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DCACP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ISOLATED_MOLECULE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LSD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.LOCAL_SPIN_DENSITY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MAXRUNTIME", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TIMESTEP_ELECTRONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TIMESTEP_IONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CMASS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPERATURE_ELECTRON", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPERATURE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPERATURE_RAMP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPERATURE_RAMP_TIME", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPERATURE_RAMP_RATE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RESCALE_OLD_VELOCITIES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.REVERSE_VELOCITIES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SUBTRACT_COMVEL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SUBTRACT_ROTVEL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SUBTRACT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PRNGSEED", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPCONTROL_IONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPCONTROL_ELECTRONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPCONTROL_CELL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TEMPCONTROL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BERENDSEN_IONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BERENDSEN_ELECTRONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BERENDSEN_CELL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS_LOCAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS_LOCAL_T0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS_LOCAL_THERMOSTATS",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS_LOCAL_RANGES",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS_CAFES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS_CAFES_GROUPS",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_CELL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_ADAPT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_ENERGY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_CALFOR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_RELAX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_RHOFIX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_INITIAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CONVERGENCE_CONSTRAINT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_IONS_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_ELECTRONS_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_CELL_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.NOSE_PARAMETERS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ANNEALING_IONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ANNEALING_ELECTRONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ANNEALING_CELL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DAMPING_IONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DAMPING_ELECTRONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DAMPING_CELL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.HESSIAN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.PROJECT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STRESS_TENSOR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STRESS_TENSOR_SAMPLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STRESS_TENSOR_VIRIAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CLASSTRESS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STORE_SELECTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STORE_INTERVAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STORE_SC_INTERVAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.STORE_OFF", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RESTFILE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RESTFILE_SAMPLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRAJECTORY_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRAJECTORY_SAMPLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TRAJECTORY_RANGE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOVIE_SAMPLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOVIE_OFF", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MOVIE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ENERGYBANDS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.EXTERNAL_POTENTIAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.EXTERNAL_POTENTIAL_ADD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ELECTROSTATIC_POTENTIAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ELECTROSTATIC_POTENTIAL_SAMPLE",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIPOLE_DYNAMICS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIPOLE_DYNAMICS_SAMPLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DIPOLE_DYNAMICS_WANNIER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RHOOUT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RHOOUT_SAMPLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RHOOUT_BANDS_COUNT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.RHOOUT_BANDS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ELF", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.ELF_PARAMETERS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.COMPRESS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MEMORY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.CHECK_MEMORY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.REAL_SPACE_WFN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.REALSPACE_WFN", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.REAL_SPACE_WFN_KEEP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.REAL_SPACE_WFN_SIZE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SPLINE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SPLINE_OPTIONS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SPLINE_POINTS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SPLINE_RANGE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FINITE_DIFFERENCE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FINITE_DIFFERENCES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TASKGROUPS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.TASKGROUPS_COUNT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.DISTRIBUTE_FNL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.FILEPATH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.BENCHMARK", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.MIRROR", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.SHIFT_POTENTIAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.cpmd.GLOC_WFNOUT_PAYLOAD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_LDA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_NONE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_SONLY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_BONLY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_BP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_BP86", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_BLYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_GGA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PW91", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PBE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_REVPBE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_HCTH", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_OPTX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_OLYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_XLYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_B3LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_B1LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PBE0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_REVPBE0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_ZPBE0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_XPBE0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PBES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_PBE1W", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_TPSS", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_HARTREE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_HARTREE_FOCK", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_HSE06", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_ACM0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_ACM1", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_ACM3", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_OLDX3LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_MODX3LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_X3LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_OLDB3LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_MODB3LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_OLDB1LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_MODB1LYP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_SAOP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_LB94", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL_GLLB", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FUNCTIONAL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.USE_CP", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.USE_LIBXC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.LSD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.GC_CUTOFF", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.LIBRARY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.KERNEL_LIBRARY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.MTS_LOW_FUNC_LIBRARY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.SCALES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.KERNEL_SCALES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.MTS_LOW_FUNC_SCALES", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.COMPATIBILITY", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.ANALYTICAL_DIV", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.NUMERICAL_DIV", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PBE_FLEX_KAPPA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PBE_FLEX_MU", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PBE_FLEX_BETA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PBE_FLEX_GAMMA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PBE_FLEX_UEG_CORRELATION",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.GRADIENT_CORRECTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HARTREE_FOCK", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HARTREE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.SLATER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.LDA_CORRELATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.OLDCODE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.NEWCODE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.XC_DRIVER", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.LIBXC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.LR_KERNEL", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.REFUNCT", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.MTS_HIGH_FUNC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.MTS_LOW_FUNC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HFX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HFX_BLOCK_SIZE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.SCALED_EXCHANGE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HFX_DISTRIBUTION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.RANGE_SEPARATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.SCREENED_EXCHANGE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.BECKE_BETA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.EXCHANGE_TABLE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HFX_SCALE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.KERNEL_HFX_SCALE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.MTS_LOW_FUNC_HFX_SCALE",
     CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PHFX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PXGC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PCGC", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PXLDA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.PCLDA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HFX_SCREENING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.ACM0", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.ACM1", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.ACM3", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.FORCE_NEW_HFX", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.SMOOTHING", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.HUBBARD", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.CORRELATION", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.EXCHANGE", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.BECKE88", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.ALPHA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"catalog.dft.BETA", CPMDC_FEATURE_KEYWORD, 1, 1},
    {"params.functional", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.cutOffRy", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.charge", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.multiplicity", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.task", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.title", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.memoryMb", CPMDC_FEATURE_PARAMS, 1, 0},
    {"params.scratchDir", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.permanentDir", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.cpmdRoot", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.enginePath", CPMDC_FEATURE_PARAMS, 1, 0},
    {"params.inputBlocks", CPMDC_FEATURE_PARAMS, 1, 1},
    {"params.inputSections", CPMDC_FEATURE_PARAMS, 1, 1},
    CPMDC_PARAM_FEATURE("params.inputSections.generic.name"),
    CPMDC_PARAM_FEATURE("params.inputSections.generic.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.atom.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.atom.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.symmetry"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.angstrom"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cellAbsolute"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cellDegree"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cellVectors"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.referenceCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.referenceCellAbsolute"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.referenceCellDegree"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.referenceCellVectors"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.classicalCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.classicalCellAbsolute"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.classicalCellDegree"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.isotropicCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.zFlexibleCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.checkSymmetryPrecision"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.checkSymmetryOff"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cutOffRy"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cutoffShape"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.hfxCutoff"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.scale"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.scaleX"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.scaleY"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.scaleZ"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.scaleCartesian"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.charge"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.multiplicity"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.nSup"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.states"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.occupation"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.occupationFixed"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.externalField"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.wCut"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.wGauss"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.couplingsFiniteDifference"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.couplingsFiniteDifferenceDisplacement"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.couplingsProductDisplacement"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.couplingsLinres"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.couplingsLinresTolerance"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.couplingsLinresNvects"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.couplingsLinresSpecify"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.couplingsLinresThresholds"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.couplingsLinresBruteForce"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.couplingsSurfaces"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.couplingsFiniteDifferenceAtoms"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cdftDonorAtoms"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cdftDonorWeights"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cdftAcceptorAtoms"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cdftAcceptorHdasDonors"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cdftAcceptorWeights"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.pointGroup"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.pointGroupMolecule"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.pointGroupDelta"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.lowSpinExcitation"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.lowSpinExcitationLsets"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.lowSpinExcitationPenalty"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.lseParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.modifiedGoedecker"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.modifiedGoedeckerParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.energyProfile"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.densityCutOffRy"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.densityCutoffNumber"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.dual"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.constantCutoff"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.boxWalls"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.poissonSolver"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.poissonParameter"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.mesh"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpoints"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsScaled"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsOnlyDiagonal"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsBlock"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsBlockAll"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsBlockCalculated"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsBlockNoSwap"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsMonkhorstPack"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.system.kpointsMonkhorstSymmetrized"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsMonkhorstFull"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsMonkhorstKdp"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointsMonkhorstShift"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.kpointBands"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.doubleGrid"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.symmetrizeCoordinates"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.tesr"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.surface"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.polymer"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.cluster"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.pressure"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.stressTensor"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.shockVelocity"),
    CPMDC_PARAM_FEATURE("params.inputSections.system.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.basis.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.basis.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.optimizeWavefunction"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamics"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceOrbitals"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.maxStep"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.timestep"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.maxRuntime"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.timestepElectrons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.timestepIons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cellMass"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceAdapt"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceEnergy"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceCalfor"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceRelax"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceRhofix"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceInitial"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceConstraint"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.temperatureElectron"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.temperature"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.temperatureRamp"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.temperatureRampTime"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.temperatureRampRate"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rescaleOldVelocities"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.reverseVelocities"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.subtractComVelocity"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.subtractRotVelocity"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prngSeed"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.tempControlIons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.tempControlElectrons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.tempControlCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.berendsenIons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.berendsenElectrons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.berendsenCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseIonsOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseIonsThermostat"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseIonsLocalT0"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.noseIonsLocalThermostatCount"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.noseIonsLocalThermostats"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.noseIonsLocalRangeCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseIonsLocalRanges"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.noseIonsCafesGroupCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseIonsCafesGroups"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseElectronsThermostat"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseCellThermostat"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.restartWavefunction"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trajectory"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.optimizeGeometry"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.optimizeGeometryOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.optimizeGeometrySample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.optimizeCombinedOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.optimizeCombinedSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.maxIter"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.convergenceGeometry"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.electronMass"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsCp"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsBo"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsEh"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsPt"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.molecularDynamicsClassical"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.molecularDynamicsFile"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.molecularDynamicsFileOptions"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.molecularDynamicsBdTrajectories"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.parrinelloRahmanOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cheby"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cayley"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rungeKutta"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.forceMatch"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nose"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseIons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noseElectrons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.berendsen"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.langevin"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.annealing"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.annealingIons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.annealingElectrons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.annealingCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.damping"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.dampingIons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.dampingElectrons"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.dampingCell"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.hessian"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.project"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.stressTensorSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.stressTensorVirial"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.classStressSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.quench"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rattle"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.shake"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.constraint"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trotter"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.restart"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.printOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.structureOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.structureSelection"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.storeOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.storeSelection"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.storeInterval"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.storeSelfConsistentInterval"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.storeOffSelection"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.restFileCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.restFileSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trajectoryOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trajectorySample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trajectoryRange"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.movieSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.movieOff"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.energyBands"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.externalPotential"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.externalPotentialAdd"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.electrostaticPotential"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.electrostaticPotentialSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.dipoleDynamics"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.dipoleDynamicsSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.dipoleDynamicsWannier"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rhoOut"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rhoOutSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rhoOutBandsCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rhoOutBands"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.elf"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.elfParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierOptimization"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierNproc"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierRelocalizeInScf"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.wannierRecomputeDipoleMatricesEvery"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierRelocalizeEvery"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierType"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierReference"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierSerial"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierDos"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierMolecular"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierWfnOutOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.wannierWfnOutPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.paraUseMpiInPlace"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.paraBuffSize"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.paraStackBuffSize"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.compress"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.memory"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.checkMemory"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.realSpaceWfn"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.realSpaceWfnKeep"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.realSpaceWfnSize"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.splineOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.splinePoints"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.splineRange"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.finiteDifferences"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.taskGroups"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.taskGroupsCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.distributeFnl"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cpGroups"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fileFusionPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fileMergePayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fileSeparationPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noReset"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.filePath"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.benchmark"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.mirror"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.shiftPotential"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.glocalizationParameters"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.glocalizationOptimization"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gfunctionalType"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.spreadRspace"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gUnitarityOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.stepTuning"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gAntisym"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gAntisymPenalty"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gKick"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gComplex"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gReal"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.readMatrix"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gStepTune"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.glocWfnOutOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.glocWfnOutPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.noGeoCheck"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.brokenSymmetry"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.distributedLinalg"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.linalgNewOrtho"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.disorthoBlockSize"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.statesBlockSize"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.allToAllPrecision"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gshell"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.localPotential"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.centerMoleculeOff"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.centerMoleculeOn"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.diis"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.odiis"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.pcg"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.diagonalization"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.freeEnergy"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.interface"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.qmmm"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.bicanonicalEnsemble"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cdft"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cdftOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cdftPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.cdftHdaPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vgfactor"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vMirror"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.combineSystemsOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.combineSystemsPayload"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.combineSystemsSabPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.kshamOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.kshamPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.czonesSet"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.woutOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.woutPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.xfmqcTrajectories"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.debugOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.kohnShamEnergiesOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.kohnShamEnergiesCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.surfaceHoppingOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.roksOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.roksExpertPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.pathSampling"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fixrhoUpwfnOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fixrhoVectors"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fixrhoLoop"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fixrhoWftol"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.bogoliubovCorrection"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vibrationalAnalysisOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vibrationalAnalysisSample"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vibrationalAnalysisMode"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.electronicSpectra"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.spinOrbitCouplingStates"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.propagationSpectra"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.propagationDistrub"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gaugePulse"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gaugeFieldFrequency"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nacv"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.orbitalHardnessOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.pathIntegral"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.pathMinimization"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.langevinOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.langevinParameter"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.qmmmEasy"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.interfaceOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trotterFactorCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.trotterFactorPayload"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.trotterFactorizationOff"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.linearResponse"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.harmonicReference"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.scaledMasses"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.tddft"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.ssic"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nonorthogonalOrbitalsOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nonorthogonalOrbitalsLimit"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.lanczosDiagonalizationOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lanczosParametersCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lanczosParametersPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.davidsonDiagonalization"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.davidsonParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.alexanderMixing"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.andersonMixingGspace"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.andersonMixingCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.andersonMixingPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.broydenMixingOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.broydenMixingPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.diisMixingCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.diisMixingPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.moverhoMixing"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.extrapolateWfnOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.extrapolateWfnOrder"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.extrapolateConstraintOrder"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.tsdeOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.tsdpOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.tcgp"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.tsdc"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.steepestDescentOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.conjugateGradientOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.odiisOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.odiisVectors"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.hamiltonianCutoff"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.gdiisVectors"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lbfgsOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lbfgsPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lbfgsNtrust"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lbfgsNrestt"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lbfgsNtrstr"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lbfgsTrustr"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoMode"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoMdlock"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoTolenv"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoTrustp"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoOmin"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoNsvib"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoCoreAtoms"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoNsmaxp"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoProjectedHessian"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoDisplacement"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.prfoHessianType"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.hesscore"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.bfgs"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rfoOrder"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.inrParametersCount"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.inrParametersPayload"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.implicitNewtonOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.implicitNewtonMaxIter"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.mixsd"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.mixdiis"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.restartOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.intFileOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.intFileName"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.initializeWavefunctionOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.rattleParameters"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.orthogonalizationOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.quenchOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.randomizeOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.randomizeAmplitude"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.useMts"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nabdyZmax"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nabdySoft"),
    CPMDC_PARAM_FEATURE(
        "params.inputSections.cpmd.nabdyRedistributeAmplitude"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nabdyScaleP"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.nabdyThermo"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.useInStream"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.useOutStream"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.useCublas"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.useCufft"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.blasNStreamsPerDevice"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.blasNDevicesPerTask"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fftNStreamsPerDevice"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.fftNDevicesPerTask"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.useMpiIo"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.traceOptions"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.traceProcedure"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.traceMaxDepth"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.traceMaxCalls"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.lsd"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.properties"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vdwCorrection"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.vdwWannier"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.dcacp"),
    CPMDC_PARAM_FEATURE("params.inputSections.cpmd.isolatedMolecule"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.functional"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.lsd"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.gcCutoff"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.xcDriver"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.libxc"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.lrKernel"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.refunct"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.mtsHighFunc"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.mtsLowFunc"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.hfx"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.hfxScreening"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.hubbard"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.alpha"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.beta"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.oldCode"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.newCode"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.correlation"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.exchange"),
    CPMDC_PARAM_FEATURE("params.inputSections.dft.becke88"),
    CPMDC_PARAM_FEATURE("params.inputSections.clas.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.clas.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.eam.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.eam.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.exte.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.exte.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.hardness.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.hardness.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.info.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.info.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.linres.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.linres.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.molstates.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.molstates.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.mts.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.mts.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.nlcc.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.nlcc.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.path.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.path.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.pimd.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.pimd.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.potential.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.potential.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.prop.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.prop.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.ptddft.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.ptddft.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.resp.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.resp.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.tddft.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.tddft.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.vdw.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.vdw.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.vectors.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.vectors.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.wavefunction.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.wavefunction.subsections"),
    CPMDC_PARAM_FEATURE("params.inputSections.atoms.pseudopotentials"),
    CPMDC_PARAM_FEATURE("params.inputSections.atoms.directives"),
    CPMDC_PARAM_FEATURE("params.inputSections.set.key"),
    CPMDC_PARAM_FEATURE("params.inputSections.set.value"),
    CPMDC_PARAM_FEATURE("params.inputSections.raw"),
    {"abi.cpmdc_set_params", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_energy_gradient", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_energy", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_energy_forces", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_create", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_set_params", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_destroy", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_energy_gradient", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_energy", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_energy_forces", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_calculate_forces", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_session_calculate_result", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_calculate_result", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_potential_result_size_for_force_input", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_version", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_available", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_finalize", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_feature_count", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_feature_table", CPMDC_FEATURE_ABI, 1, 1},
    {"abi.cpmdc_feature_find", CPMDC_FEATURE_ABI, 1, 1},
};

#undef CPMDC_PARAM_FEATURE

size_t cpmdc_feature_count(void) {
  return sizeof(g_features) / sizeof(g_features[0]);
}

const CPMDCFeatureEntry *cpmdc_feature_table(void) { return g_features; }

const CPMDCFeatureEntry *cpmdc_feature_find(const char *feature_id) {
  if (!feature_id) return NULL;
  size_t n = cpmdc_feature_count();
  for (size_t i = 0; i < n; ++i) {
    if (strcmp(g_features[i].feature_id, feature_id) == 0)
      return &g_features[i];
  }
  return NULL;
}
